apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "spring-chart.fullname" . }}
  labels:
    {{- include "spring-chart.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "spring-chart.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "spring-chart.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: spring-lab

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.container.port }}

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"

          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: 15
            periodSeconds: 5

          resources:
            {{- toYaml .Values.resources | nindent 12 }}