apiVersion: v1
kind: Service

metadata:
  name: spring-lab

spec:

  selector:
    app: spring-lab

  ports:

    - protocol: TCP

      port: 80

      targetPort: 80

  type: ClusterIP
apiVersion: v1
kind: Service

metadata:
  name: spring-lab

spec:
  selector:
    app: spring-lab

  ports:
    - port: 8081
      targetPort: 8081

  type: ClusterIP
