apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-lab

spec:
  replicas: 1

  selector:
    matchLabels:
      app: spring-lab

  template:
    metadata:
      labels:
        app: spring-lab

    spec:
      containers:
        - name: spring-lab
          image: ghcr.io/alinicanedo/spring-lab:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8081